name: QArunBackTests

on:
  push:
    branches:
      - QA

jobs:
  acciones_condicionales:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Instalar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Ejecutar pruebas unitarias
        run: |
          cd BACK/hu-tp-01-001
          npm install
          npm test
