name: Test Workflow

on:
  push:
    branches:
      - QA

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Imprimir mensaje de prueba
        run: echo "Workflow ejecutado correctamente"
