name: Push to MAIN_FIAFIT

on:
  push:
    branches:
      - main

jobs:
  push_to_dev:
    runs-on: ubuntu-latest

    steps:
    # Checkout the current repository (MAIN_FIAFIT)
    - name: Checkout MAIN_FIAFIT
      uses: actions/checkout@v2

    # Configurar Git con las credenciales
    - name: Set up Git
      run: |
        git config --global user.name 'gonzalo1998peru'
        git config --global user.email 'gonzalo_huertas_oliva@outlook.es'

    # Clone the MAIN_FIAFIT repository (branch 'DEV') into TEMPORAL_CHANGE directory
    - name: Clone MAIN_PROYFIAFIT
      run: |
        git clone --branch DEV https://x-access-token:${{ secrets.access_token_gonzalo }}@github.com/TP-PROYECTOGIMNASIO/MAIN_PROYFIAFIT.git TEMPORAL_CHANGE

      # Copy files from BACKEND_FIAFIT to MAIN_PROYFIAFIT
    - name: Copy files from MAIN_FIAFIT to MAIN_PROYFIAFIT
      run: |
        rsync -av --exclude='.git' --exclude='.github/workflows' --exclude='TEMPORAL_CHANGE' ./ TEMPORAL_CHANGE/
        cd TEMPORAL_CHANGE
        git add .
        git commit -m "Sync from MAIN_FIAFIT"
        git push
