name: Sync FRONT to DEV

on:
  push:
    branches:
      - FRONT

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del repositorio con todas las ramas
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Trae todas las ramas y commits del historial completo

      # Paso 2: Configura Git
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Paso 3: Listar las ramas disponibles
      - name: List branches
        run: git branch -a

      # Paso 4: Merge FRONT en DEV con --allow-unrelated-histories
      - name: Merge FRONT into DEV using theirs strategy
        run: |
          git checkout DEV
          git merge -X theirs FRONT
          git push origin DEV

